#############################################################################
# Makefile for building: Smarthings
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  Smarthings.pro
# Template: app
# Command: /opt/Qt/5.8/gcc_64/bin/qmake -o Makefile Smarthings.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_SERIALPORT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/Qt/5.8/gcc_64/include -I/opt/Qt/5.8/gcc_64/include/QtSerialPort -I/opt/Qt/5.8/gcc_64/include/QtNetwork -I/opt/Qt/5.8/gcc_64/include/QtCore -I. -I/opt/Qt/5.8/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/Qt/5.8/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Smarthings1.0.0
DISTDIR = /home/marssola/Developers/Smarthings/Smarthings/.tmp/Smarthings1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/Qt/5.8/gcc_64/lib
LIBS          = $(SUBLIBS) -L/opt/Qt/5.8/gcc_64/lib -lQt5SerialPort -lQt5Network -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cpp/udp/udpserver.cpp \
		cpp/tcp/tcpserver.cpp \
		cpp/tcp/tcpconnection.cpp \
		cpp/serial/serialserver.cpp moc_udpserver.cpp \
		moc_tcpserver.cpp \
		moc_tcpconnection.cpp \
		moc_serialserver.cpp
OBJECTS       = main.o \
		udpserver.o \
		tcpserver.o \
		tcpconnection.o \
		serialserver.o \
		moc_udpserver.o \
		moc_tcpserver.o \
		moc_tcpconnection.o \
		moc_serialserver.o
DIST          = /opt/Qt/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/toolchain.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/lex.prf \
		Smarthings.pro cpp/udp/udpserver.h \
		cpp/tcp/tcpserver.h \
		cpp/tcp/tcpconnection.h \
		cpp/serial/serialserver.h main.cpp \
		cpp/udp/udpserver.cpp \
		cpp/tcp/tcpserver.cpp \
		cpp/tcp/tcpconnection.cpp \
		cpp/serial/serialserver.cpp
QMAKE_TARGET  = Smarthings
DESTDIR       = 
TARGET        = Smarthings


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Smarthings.pro /opt/Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/toolchain.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.8/gcc_64/mkspecs/features/lex.prf \
		Smarthings.pro \
		/opt/Qt/5.8/gcc_64/lib/libQt5SerialPort.prl \
		/opt/Qt/5.8/gcc_64/lib/libQt5Network.prl \
		/opt/Qt/5.8/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Smarthings.pro
/opt/Qt/5.8/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt/5.8/gcc_64/mkspecs/common/unix.conf:
/opt/Qt/5.8/gcc_64/mkspecs/common/linux.conf:
/opt/Qt/5.8/gcc_64/mkspecs/common/sanitize.conf:
/opt/Qt/5.8/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt/5.8/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt/5.8/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt/5.8/gcc_64/mkspecs/qconfig.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt/5.8/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt/5.8/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/Qt/5.8/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/toolchain.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/qt.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/resources.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/moc.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/qmake_use.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/file_copies.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt/5.8/gcc_64/mkspecs/features/lex.prf:
Smarthings.pro:
/opt/Qt/5.8/gcc_64/lib/libQt5SerialPort.prl:
/opt/Qt/5.8/gcc_64/lib/libQt5Network.prl:
/opt/Qt/5.8/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Smarthings.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/Qt/5.8/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents cpp/udp/udpserver.h cpp/tcp/tcpserver.h cpp/tcp/tcpconnection.h cpp/serial/serialserver.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp cpp/udp/udpserver.cpp cpp/tcp/tcpserver.cpp cpp/tcp/tcpconnection.cpp cpp/serial/serialserver.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/Qt/5.8/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /opt/Qt/5.8/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_udpserver.cpp moc_tcpserver.cpp moc_tcpconnection.cpp moc_serialserver.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_udpserver.cpp moc_tcpserver.cpp moc_tcpconnection.cpp moc_serialserver.cpp
moc_udpserver.cpp: /opt/Qt/5.8/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/QUdpSocket \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qudpsocket.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qhostaddress.h \
		cpp/udp/udpserver.h \
		moc_predefs.h \
		/opt/Qt/5.8/gcc_64/bin/moc
	/opt/Qt/5.8/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/opt/Qt/5.8/gcc_64/mkspecs/linux-g++ -I/home/marssola/Developers/Smarthings/Smarthings -I/opt/Qt/5.8/gcc_64/include -I/opt/Qt/5.8/gcc_64/include/QtSerialPort -I/opt/Qt/5.8/gcc_64/include/QtNetwork -I/opt/Qt/5.8/gcc_64/include/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include cpp/udp/udpserver.h -o moc_udpserver.cpp

moc_tcpserver.cpp: /opt/Qt/5.8/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/QTcpServer \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtcpserver.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qhostaddress.h \
		cpp/tcp/tcpconnection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/QDebug \
		/opt/Qt/5.8/gcc_64/include/QtCore/QThread \
		/opt/Qt/5.8/gcc_64/include/QtCore/qthread.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/QTcpSocket \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtcpsocket.h \
		cpp/tcp/tcpserver.h \
		moc_predefs.h \
		/opt/Qt/5.8/gcc_64/bin/moc
	/opt/Qt/5.8/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/opt/Qt/5.8/gcc_64/mkspecs/linux-g++ -I/home/marssola/Developers/Smarthings/Smarthings -I/opt/Qt/5.8/gcc_64/include -I/opt/Qt/5.8/gcc_64/include/QtSerialPort -I/opt/Qt/5.8/gcc_64/include/QtNetwork -I/opt/Qt/5.8/gcc_64/include/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include cpp/tcp/tcpserver.h -o moc_tcpserver.cpp

moc_tcpconnection.cpp: /opt/Qt/5.8/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/QDebug \
		/opt/Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/QThread \
		/opt/Qt/5.8/gcc_64/include/QtCore/qthread.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/QTcpSocket \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtcpsocket.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		cpp/tcp/tcpconnection.h \
		moc_predefs.h \
		/opt/Qt/5.8/gcc_64/bin/moc
	/opt/Qt/5.8/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/opt/Qt/5.8/gcc_64/mkspecs/linux-g++ -I/home/marssola/Developers/Smarthings/Smarthings -I/opt/Qt/5.8/gcc_64/include -I/opt/Qt/5.8/gcc_64/include/QtSerialPort -I/opt/Qt/5.8/gcc_64/include/QtNetwork -I/opt/Qt/5.8/gcc_64/include/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include cpp/tcp/tcpconnection.h -o moc_tcpconnection.cpp

moc_serialserver.cpp: /opt/Qt/5.8/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/QSerialPort \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/qserialport.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/qserialportglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/QSerialPortInfo \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/qserialportinfo.h \
		cpp/serial/serialserver.h \
		moc_predefs.h \
		/opt/Qt/5.8/gcc_64/bin/moc
	/opt/Qt/5.8/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/opt/Qt/5.8/gcc_64/mkspecs/linux-g++ -I/home/marssola/Developers/Smarthings/Smarthings -I/opt/Qt/5.8/gcc_64/include -I/opt/Qt/5.8/gcc_64/include/QtSerialPort -I/opt/Qt/5.8/gcc_64/include/QtNetwork -I/opt/Qt/5.8/gcc_64/include/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include cpp/serial/serialserver.h -o moc_serialserver.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /opt/Qt/5.8/gcc_64/include/QtCore/QCoreApplication \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/QThread \
		/opt/Qt/5.8/gcc_64/include/QtCore/qthread.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.8/gcc_64/include/QtCore/QMutex \
		cpp/udp/udpserver.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/QUdpSocket \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qudpsocket.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qhostaddress.h \
		cpp/tcp/tcpserver.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/QTcpServer \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtcpserver.h \
		cpp/tcp/tcpconnection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/QDebug \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/QTcpSocket \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtcpsocket.h \
		cpp/serial/serialserver.h \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/QSerialPort \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/qserialport.h \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/qserialportglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/QSerialPortInfo \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/qserialportinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

udpserver.o: cpp/udp/udpserver.cpp cpp/udp/udpserver.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/QUdpSocket \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qudpsocket.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qhostaddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o udpserver.o cpp/udp/udpserver.cpp

tcpserver.o: cpp/tcp/tcpserver.cpp cpp/tcp/tcpserver.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/QTcpServer \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtcpserver.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qhostaddress.h \
		cpp/tcp/tcpconnection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/QDebug \
		/opt/Qt/5.8/gcc_64/include/QtCore/QThread \
		/opt/Qt/5.8/gcc_64/include/QtCore/qthread.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/QTcpSocket \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtcpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpserver.o cpp/tcp/tcpserver.cpp

tcpconnection.o: cpp/tcp/tcpconnection.cpp cpp/tcp/tcpconnection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/QDebug \
		/opt/Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/QThread \
		/opt/Qt/5.8/gcc_64/include/QtCore/qthread.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/QTcpSocket \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtcpsocket.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/opt/Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpconnection.o cpp/tcp/tcpconnection.cpp

serialserver.o: cpp/serial/serialserver.cpp cpp/serial/serialserver.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/QSerialPort \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/qserialport.h \
		/opt/Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/qserialportglobal.h \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/QSerialPortInfo \
		/opt/Qt/5.8/gcc_64/include/QtSerialPort/qserialportinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialserver.o cpp/serial/serialserver.cpp

moc_udpserver.o: moc_udpserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_udpserver.o moc_udpserver.cpp

moc_tcpserver.o: moc_tcpserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpserver.o moc_tcpserver.cpp

moc_tcpconnection.o: moc_tcpconnection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpconnection.o moc_tcpconnection.cpp

moc_serialserver.o: moc_serialserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialserver.o moc_serialserver.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

