#############################################################################
# Makefile for building: Smarthings
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  Smarthings.pro
# Template: app
# Command: /Users/mauro/Qt/5.8/clang_64/bin/qmake -o Makefile Smarthings.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -O2 -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I../../Qt/5.8/clang_64/mkspecs/macx-clang -F/Users/mauro/Qt/5.8/clang_64/lib
QMAKE         = /Users/mauro/Qt/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Smarthings1.0.0
DISTDIR = /Users/mauro/Developer/Smarthings/.tmp/Smarthings1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,/Users/mauro/Qt/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/mauro/Qt/5.8/clang_64/lib -framework QtCore -framework DiskArbitration -framework IOKit 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cpp/tcp/tcpserver.cpp \
		cpp/udp/udpserver.cpp \
		cpp/tcp/tcpserver.cpp \
		cpp/udp/udpserver.cpp \
		cpp/general/connectiondatabase.cpp \
		cpp/general/connectiondatabase.cpp \
		cpp/serial/serialserver.cpp \
		cpp/serial/serialserver.cpp moc_tcpserver.cpp \
		moc_udpserver.cpp \
		moc_connectiondatabase.cpp \
		moc_serialserver.cpp
OBJECTS       = main.o \
		tcpserver.o \
		udpserver.o \
		tcpserver.o \
		udpserver.o \
		connectiondatabase.o \
		connectiondatabase.o \
		serialserver.o \
		serialserver.o \
		moc_tcpserver.o \
		moc_udpserver.o \
		moc_connectiondatabase.o \
		moc_serialserver.o
DIST          = ../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.8/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.8/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.8/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.8/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.8/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.8/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.8/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.8/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.8/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.8/clang_64/mkspecs/features/lex.prf \
		Smarthings.pro cpp/tcp/tcpserver.h \
		cpp/udp/udpserver.h \
		cpp/tcp/tcpserver.h \
		cpp/udp/udpserver.h \
		cpp/general/connectiondatabase.h \
		cpp/general/connectiondatabase.h \
		cpp/serial/serialserver.h \
		cpp/serial/serialserver.h main.cpp \
		cpp/tcp/tcpserver.cpp \
		cpp/udp/udpserver.cpp \
		cpp/tcp/tcpserver.cpp \
		cpp/udp/udpserver.cpp \
		cpp/general/connectiondatabase.cpp \
		cpp/general/connectiondatabase.cpp \
		cpp/serial/serialserver.cpp \
		cpp/serial/serialserver.cpp
QMAKE_TARGET  = Smarthings
DESTDIR       = 
TARGET        = Smarthings


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Smarthings.pro ../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.8/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.8/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.8/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.8/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.8/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.8/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.8/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.8/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.8/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.8/clang_64/mkspecs/features/lex.prf \
		Smarthings.pro \
		../../Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Smarthings.pro
../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.8/clang_64/mkspecs/qdevice.pri:
../../Qt/5.8/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.8/clang_64/mkspecs/common/unix.conf:
../../Qt/5.8/clang_64/mkspecs/common/mac.conf:
../../Qt/5.8/clang_64/mkspecs/common/macx.conf:
../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf:
../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.8/clang_64/mkspecs/common/clang.conf:
../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.8/clang_64/mkspecs/qconfig.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf:
../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.8/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.8/clang_64/mkspecs/features/qt.prf:
../../Qt/5.8/clang_64/mkspecs/features/resources.prf:
../../Qt/5.8/clang_64/mkspecs/features/moc.prf:
../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf:
../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.8/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.8/clang_64/mkspecs/features/lex.prf:
Smarthings.pro:
../../Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Smarthings.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents cpp/tcp/tcpserver.h cpp/udp/udpserver.h cpp/tcp/tcpserver.h cpp/udp/udpserver.h cpp/general/connectiondatabase.h cpp/general/connectiondatabase.h cpp/serial/serialserver.h cpp/serial/serialserver.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp cpp/tcp/tcpserver.cpp cpp/udp/udpserver.cpp cpp/tcp/tcpserver.cpp cpp/udp/udpserver.cpp cpp/general/connectiondatabase.cpp cpp/general/connectiondatabase.cpp cpp/serial/serialserver.cpp cpp/serial/serialserver.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_tcpserver.cpp moc_udpserver.cpp moc_tcpserver.cpp moc_udpserver.cpp moc_connectiondatabase.cpp moc_connectiondatabase.cpp moc_serialserver.cpp moc_serialserver.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_tcpserver.cpp moc_udpserver.cpp moc_tcpserver.cpp moc_udpserver.cpp moc_connectiondatabase.cpp moc_connectiondatabase.cpp moc_serialserver.cpp moc_serialserver.cpp
moc_tcpserver.cpp: ../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		cpp/tcp/tcpserver.h \
		moc_predefs.h \
		../../Qt/5.8/clang_64/bin/moc
	/Users/mauro/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/mauro/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/mauro/Developer/Smarthings -I/Users/mauro/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/mauro/Qt/5.8/clang_64/lib cpp/tcp/tcpserver.h -o moc_tcpserver.cpp

moc_udpserver.cpp: ../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		cpp/udp/udpserver.h \
		moc_predefs.h \
		../../Qt/5.8/clang_64/bin/moc
	/Users/mauro/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/mauro/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/mauro/Developer/Smarthings -I/Users/mauro/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/mauro/Qt/5.8/clang_64/lib cpp/udp/udpserver.h -o moc_udpserver.cpp

moc_tcpserver.cpp: ../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		cpp/tcp/tcpserver.h \
		moc_predefs.h \
		../../Qt/5.8/clang_64/bin/moc
	/Users/mauro/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/mauro/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/mauro/Developer/Smarthings -I/Users/mauro/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/mauro/Qt/5.8/clang_64/lib cpp/tcp/tcpserver.h -o moc_tcpserver.cpp

moc_udpserver.cpp: ../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		cpp/udp/udpserver.h \
		moc_predefs.h \
		../../Qt/5.8/clang_64/bin/moc
	/Users/mauro/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/mauro/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/mauro/Developer/Smarthings -I/Users/mauro/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/mauro/Qt/5.8/clang_64/lib cpp/udp/udpserver.h -o moc_udpserver.cpp

moc_connectiondatabase.cpp: ../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		cpp/general/connectiondatabase.h \
		moc_predefs.h \
		../../Qt/5.8/clang_64/bin/moc
	/Users/mauro/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/mauro/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/mauro/Developer/Smarthings -I/Users/mauro/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/mauro/Qt/5.8/clang_64/lib cpp/general/connectiondatabase.h -o moc_connectiondatabase.cpp

moc_connectiondatabase.cpp: ../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		cpp/general/connectiondatabase.h \
		moc_predefs.h \
		../../Qt/5.8/clang_64/bin/moc
	/Users/mauro/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/mauro/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/mauro/Developer/Smarthings -I/Users/mauro/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/mauro/Qt/5.8/clang_64/lib cpp/general/connectiondatabase.h -o moc_connectiondatabase.cpp

moc_serialserver.cpp: ../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		cpp/serial/serialserver.h \
		moc_predefs.h \
		../../Qt/5.8/clang_64/bin/moc
	/Users/mauro/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/mauro/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/mauro/Developer/Smarthings -I/Users/mauro/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/mauro/Qt/5.8/clang_64/lib cpp/serial/serialserver.h -o moc_serialserver.cpp

moc_serialserver.cpp: ../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		cpp/serial/serialserver.h \
		moc_predefs.h \
		../../Qt/5.8/clang_64/bin/moc
	/Users/mauro/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/mauro/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/mauro/Developer/Smarthings -I/Users/mauro/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/mauro/Qt/5.8/clang_64/lib cpp/serial/serialserver.h -o moc_serialserver.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

tcpserver.o: cpp/tcp/tcpserver.cpp cpp/tcp/tcpserver.h \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpserver.o cpp/tcp/tcpserver.cpp

udpserver.o: cpp/udp/udpserver.cpp cpp/udp/udpserver.h \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o udpserver.o cpp/udp/udpserver.cpp

tcpserver.o: cpp/tcp/tcpserver.cpp cpp/tcp/tcpserver.h \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpserver.o cpp/tcp/tcpserver.cpp

udpserver.o: cpp/udp/udpserver.cpp cpp/udp/udpserver.h \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o udpserver.o cpp/udp/udpserver.cpp

connectiondatabase.o: cpp/general/connectiondatabase.cpp cpp/general/connectiondatabase.h \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectiondatabase.o cpp/general/connectiondatabase.cpp

connectiondatabase.o: cpp/general/connectiondatabase.cpp cpp/general/connectiondatabase.h \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectiondatabase.o cpp/general/connectiondatabase.cpp

serialserver.o: cpp/serial/serialserver.cpp cpp/serial/serialserver.h \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialserver.o cpp/serial/serialserver.cpp

serialserver.o: cpp/serial/serialserver.cpp cpp/serial/serialserver.h \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialserver.o cpp/serial/serialserver.cpp

moc_tcpserver.o: moc_tcpserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpserver.o moc_tcpserver.cpp

moc_udpserver.o: moc_udpserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_udpserver.o moc_udpserver.cpp

moc_connectiondatabase.o: moc_connectiondatabase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connectiondatabase.o moc_connectiondatabase.cpp

moc_serialserver.o: moc_serialserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialserver.o moc_serialserver.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

